version: '3.8'

services:

  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080" # Dashboard do Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-net

  mongodb:
    image: mongo:latest
    container_name: mongodb_cypher
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cypher

volumes:
  mongodb_data:
    driver: local

networks:
  traefik-net:
    driver: bridge